# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  registerapiproject:
    container_name: dotnet
    # image: my-image:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings:DefaultConnection=Server=localhost;Database=registerDb;User=root;Password=password;
    ports:
      - 8081:8080

    command: dotnet ef database update
